site_name: Discord4J
theme: readthedocs
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started':
    - 'Getting Started': 'Getting-Started.md'
    - 'Lambda Tutorial': 'Lambda-Tutorial.md'
    - 'Reactor (Reactive) Tutorial': 'Reactive-(Reactor)-Tutorial.md'
    - 'Basic Bot Tutorial': 'Basic-Bot-Tutorial.md'
    - 'Music Bot Tutorial (v3.0+)': 'Music-Bot-Tutorial.md'
    - 'Frequently Asked Questions': 'Frequently-Asked-Questions.md'
    - 'Migrating from v2.x to v3.1': 'Migrating-from-v2.x-to-v3.1.md'
  - 'Exploring the API':
    - 'Specs': 'Specs.md'
  - 'Advanced':
    - 'Sharding': 'Sharding.md'
    - 'Logging': 'Logging.md'
    - 'Threading': 'Threading.md'
    - 'Error Handling': 'Error-Handling.md'
    - 'Using Jitpack': 'Using-Jitpack.md'
    - 'Using latest snapshots': 'Using-latest-snapshots.md'
    - 'Using our BOM': 'Using-the-BOM.md'